INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'NOBODY');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'NOBODY');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'FELLOWSHIP');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'FELLOWSHIP');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'TWO TOWERS');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'TWO TOWERS');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'RETURN KING');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'RETURN KING');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'OFFICE SPACE');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'OFFICE SPACE');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'ALIEN');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'ALIEN');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'ALIENS');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'ALIENS');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'C', 'BUCKAROO BANZAI');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'C', 'BUCKAROO BANZAI');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'C', 'MUMMY');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'C', 'MUMMY');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'MAD MAX');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'MAD MAX');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'C', 'WILDERPEOPLE');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'C', 'WILDERPEOPLE');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'RED OCTOBER');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'RED OCTOBER');

SET DEFINE OFF;
INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'BILL & TED');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'BILL & TED');
SET DEFINE ON;

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'A NEW HOPE');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'A NEW HOPE');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'STRIKES BACK');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'STRIKES BACK');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'THE MARTIAN');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'THE MARTIAN');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'APOLLO 13');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'APOLLO 13');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'JURASSIC PARK');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'JURASSIC PARK');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'A', 'THE MATRIX');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'A', 'THE MATRIX');

INSERT INTO DDR_TITLE_PRICE VALUES ('HD', 'B', 'PREDATOR');
INSERT INTO DDR_TITLE_PRICE VALUES ('SD', 'B', 'PREDATOR');