INSERT INTO DDR_PRICE VALUES ('SD', 'A', 5.99);
INSERT INTO DDR_PRICE VALUES ('HD', 'A', 6.99);
INSERT INTO DDR_PRICE VALUES ('SD', 'B', 3.99);
INSERT INTO DDR_PRICE VALUES ('HD', 'B', 4.99);
INSERT INTO DDR_PRICE VALUES ('SD', 'C', 0.99);
INSERT INTO DDR_PRICE VALUES ('HD', 'C', 1.99);