INSERT INTO DDR_TITLE_CAST VALUES (1, 'NOBODY');
INSERT INTO DDR_TITLE_CAST VALUES (2, 'NOBODY');

INSERT INTO DDR_TITLE_CAST VALUES (3, 'FELLOWSHIP');
INSERT INTO DDR_TITLE_CAST VALUES (4, 'FELLOWSHIP');
INSERT INTO DDR_TITLE_CAST VALUES (5, 'FELLOWSHIP');
INSERT INTO DDR_TITLE_CAST VALUES (6, 'FELLOWSHIP');
INSERT INTO DDR_TITLE_CAST VALUES (7, 'FELLOWSHIP');

INSERT INTO DDR_TITLE_CAST VALUES (3, 'TWO TOWERS');
INSERT INTO DDR_TITLE_CAST VALUES (4, 'TWO TOWERS');
INSERT INTO DDR_TITLE_CAST VALUES (5, 'TWO TOWERS');
INSERT INTO DDR_TITLE_CAST VALUES (6, 'TWO TOWERS');
INSERT INTO DDR_TITLE_CAST VALUES (7, 'TWO TOWERS');

INSERT INTO DDR_TITLE_CAST VALUES (3, 'RETURN KING');
INSERT INTO DDR_TITLE_CAST VALUES (4, 'RETURN KING');
INSERT INTO DDR_TITLE_CAST VALUES (5, 'RETURN KING');
INSERT INTO DDR_TITLE_CAST VALUES (6, 'RETURN KING');
INSERT INTO DDR_TITLE_CAST VALUES (7, 'RETURN KING');

INSERT INTO DDR_TITLE_CAST VALUES (8, 'OFFICE SPACE');
INSERT INTO DDR_TITLE_CAST VALUES (9, 'OFFICE SPACE');

INSERT INTO DDR_TITLE_CAST VALUES (10, 'ALIEN');
INSERT INTO DDR_TITLE_CAST VALUES (11, 'ALIEN');

INSERT INTO DDR_TITLE_CAST VALUES (10, 'ALIENS');
INSERT INTO DDR_TITLE_CAST VALUES (12, 'ALIENS');
INSERT INTO DDR_TITLE_CAST VALUES (13, 'ALIENS');
INSERT INTO DDR_TITLE_CAST VALUES (14, 'ALIENS');

INSERT INTO DDR_TITLE_CAST VALUES (15, 'BUCKAROO BANZAI');
INSERT INTO DDR_TITLE_CAST VALUES (16, 'BUCKAROO BANZAI');
INSERT INTO DDR_TITLE_CAST VALUES (17, 'BUCKAROO BANZAI');

INSERT INTO DDR_TITLE_CAST VALUES (18, 'MUMMY');
INSERT INTO DDR_TITLE_CAST VALUES (19, 'MUMMY');
INSERT INTO DDR_TITLE_CAST VALUES (20, 'MUMMY');

INSERT INTO DDR_TITLE_CAST VALUES (21, 'MAD MAX');
INSERT INTO DDR_TITLE_CAST VALUES (22, 'MAD MAX');
INSERT INTO DDR_TITLE_CAST VALUES (23, 'MAD MAX');

INSERT INTO DDR_TITLE_CAST VALUES (24, 'WILDERPEOPLE');
INSERT INTO DDR_TITLE_CAST VALUES (25, 'WILDERPEOPLE');

INSERT INTO DDR_TITLE_CAST VALUES (24, 'RED OCTOBER');
INSERT INTO DDR_TITLE_CAST VALUES (26, 'RED OCTOBER');
INSERT INTO DDR_TITLE_CAST VALUES (27, 'RED OCTOBER');

SET DEFINE OFF;
INSERT INTO DDR_TITLE_CAST VALUES (28, 'BILL & TED');
INSERT INTO DDR_TITLE_CAST VALUES (29, 'BILL & TED');
SET DEFINE ON;

INSERT INTO DDR_TITLE_CAST VALUES (30, 'A NEW HOPE');
INSERT INTO DDR_TITLE_CAST VALUES (31, 'A NEW HOPE');
INSERT INTO DDR_TITLE_CAST VALUES (32, 'A NEW HOPE');
INSERT INTO DDR_TITLE_CAST VALUES (33, 'A NEW HOPE');

INSERT INTO DDR_TITLE_CAST VALUES (30, 'STRIKES BACK');
INSERT INTO DDR_TITLE_CAST VALUES (31, 'STRIKES BACK');
INSERT INTO DDR_TITLE_CAST VALUES (32, 'STRIKES BACK');
INSERT INTO DDR_TITLE_CAST VALUES (33, 'STRIKES BACK');

INSERT INTO DDR_TITLE_CAST VALUES (34, 'THE MARTIAN');

INSERT INTO DDR_TITLE_CAST VALUES (35, 'APOLLO 13');
INSERT INTO DDR_TITLE_CAST VALUES (36, 'APOLLO 13');
INSERT INTO DDR_TITLE_CAST VALUES (13, 'APOLLO 13');

INSERT INTO DDR_TITLE_CAST VALUES (16, 'JURASSIC PARK');
INSERT INTO DDR_TITLE_CAST VALUES (24, 'JURASSIC PARK');
INSERT INTO DDR_TITLE_CAST VALUES (37, 'JURASSIC PARK');
INSERT INTO DDR_TITLE_CAST VALUES (38, 'JURASSIC PARK');

INSERT INTO DDR_TITLE_CAST VALUES (28, 'THE MATRIX');
INSERT INTO DDR_TITLE_CAST VALUES (39, 'THE MATRIX');
INSERT INTO DDR_TITLE_CAST VALUES (40, 'THE MATRIX');
INSERT INTO DDR_TITLE_CAST VALUES (41, 'THE MATRIX');

INSERT INTO DDR_TITLE_CAST VALUES (42, 'PREDATOR');
INSERT INTO DDR_TITLE_CAST VALUES (43, 'PREDATOR');